### ISSUE TITLE
Landing broken

### ISSUE THREAD

**Issue by jimlongo56** [tmcw/docbox#77] opened 2018-02-22 17:35 UTC
Starting from scratch.

Clone repo, install, test . . . everything passes.
build, no errors.
display resultant index.html in Chrome

Upon loading I get this
![screen shot 2018-02-22 at 12 32 26 pm](https://user-images.githubusercontent.com/6787988/36554249-ba522e60-17cc-11e8-815b-f04ef23ac67e.png)

If I drag the browser window narrower so a breakpoint kicks in, then expand the page again everything snaps into place correctly.
![screen shot 2018-02-22 at 12 32 39 pm](https://user-images.githubusercontent.com/6787988/36554282-d5cbb094-17cc-11e8-9669-48239ff3f5f6.png)

**Comment by tmcw** [comment] 2018-02-22 17:36
Yep, that's #64, and this is a duplicate of that issue.

**Closed by tmcw** 2018-02-22 17:36 UTC
